### ISSUE TITLE
om/update-state! causes "No queries exist for component path" on alpha35,34,etc 

### ISSUE THREAD

**Issue by jasonjckn** [omcljs/om#687] opened 2016-05-21 02:45 UTC
When you double click the label in this program I get this exception:

```
next.cljs:1268 Uncaught #error {:message "No queries exist for component path (om-todomvc.core/RootView om-todomvc.core/MainView om-todomvc.core/TodoList om-todomvc.core/TodoItem) or data path [:widget/root :widget/main [:todo-list/by-id 1]]", :data {:type :om.next/no-queries}}
```

(the program loads fine, it only errors when update-state! is called on double click)

```clojure
(ns om-todomvc.core
  (:require
   [cljs.pprint :refer [pprint]]
   [cljs.core.match :refer-macros [match]]
   [sablono.core :as html :refer-macros [html] :refer [text-field]]
   [om.next :as om :refer-macros [defui ui]]
   [om.dom :as dom]))

(defui TodoItem
  static om/IQuery
  (query [T]
         '[:todo/title :todo/id])

  Object
  (render [T]
          (let [on-double-click #(om/update-state! T assoc :edit-mode? true)]
            (dom/label #js {:onDoubleClick on-double-click}
                       (dom/b nil "double click me; ")))))

(def todo-item (om/factory TodoItem {:keyfn :todo/id}))

(defui TodoList
  static om/IQuery
  (query [T] `[{[:todo-list/by-id 1] ~(om/get-query TodoItem)}])

  Object
  (render [T]
          (let [items ((om/props T) [:todo-list/by-id 1])]
            (apply dom/div nil
                   (for [item items]
                     (todo-item item))))))

(def todo-list (om/factory TodoList))

(defui MainView
  static om/IQuery
  (query [T]
         `[{:widget/main ~(om/get-query TodoList)}])
  Object
  (render [T]
          (let [{:keys [widget/main]} (om/props T)]
            (todo-list main))))

(def main-view (om/factory MainView))

(defui RootView
  static om/IQuery
  (query [T]
         `[{:widget/root ~(om/get-query MainView)}])
  Object
  (render [T]
          (let [{:keys [widget/root]} (om/props T)]
            (main-view root))))


(defmulti read om/dispatch)
(defmulti mutate om/dispatch)

(defmethod read :default
  [{:keys [state query ast parser] :as env} key _]
  (condp = (namespace key)
    "widget" {:value (parser env query)}))

(defmethod read :todo-list/by-id
  [{:keys [state query ast parser query-root] :as env} key _]
  {:value (om/db->tree query (get-in @state query-root) @state)})

(def state (atom {:todo/by-id {1 {:todo/id 1 :todo/title "got milk?"}
                               2 {:todo/id 2 :todo/title "bar"}}

                  :todo-list/by-id {1 [[:todo/by-id 1]
                                       [:todo/by-id 2]]}}))

(def parser (om/parser {:read read :mutate mutate}))

(defonce reconciler
  (om/reconciler {:state state
                  :parser parser
                  :remotes []}))

(om/add-root! reconciler
              RootView (js/document.getElementById "app"))
```

**Comment by anmonteiro** [comment] 2016-05-21 13:42
This is a duplicate of #605

**Comment by swannodette** [comment] 2016-05-21 20:53
fixed https://github.com/omcljs/om/commit/8cf520a425afbc31ae8b7d79289addbfaa68c86e

**Closed by swannodette** 2016-05-21 20:53 UTC
