### ISSUE TITLE
Om.next wiki: Ensure user REPL (in-ns 'om-tutorial.core)

### ISSUE THREAD

**Issue by felixflores** [omcljs/om#390] opened 2015-10-07 05:30 UTC
In your the example:

```
Copy and paste one of the UUIDs and try the following at the REPL (your UUID will be different!):

(om/from-history reconciler
  #uuid "9e7160a0-89cc-4482-aba1-7b894a1c54b4")
;; => {:count 2}
```

ensure that the user is in the proper namespace

```
Copy and paste one of the UUIDs and try the following at the REPL (your UUID will be different!):

(in-ns 'om-tutorial.core)
(om/from-history reconciler
  #uuid "9e7160a0-89cc-4482-aba1-7b894a1c54b4")
;; => {:count 2}
```

**Comment by swannodette** [comment] 2015-10-08 13:08
dupe of 391

**Closed by swannodette** 2015-10-08 13:08 UTC
