### ISSUE TITLE
`db->tree` doesn't follow ident chain

### ISSUE THREAD

**Issue by anmonteiro** [omcljs/om#708] opened 2016-06-30 22:44 UTC
```clojure
(let [data {:a [:b 1]
            :b {1 [:c 2]}
            :c {2 {:foo "bar"}}}]
  (om/db->tree [{:a [:foo]}] data data))
```

**Comment by swannodette** [comment] 2016-07-07 21:19
dupe of #710 no?

**Comment by anmonteiro** [comment] 2016-07-07 21:33
Yea, the PR fixed both, this can be closed

**Closed** 2016-07-07 21:38 UTC
